### ISSUE TITLE
create electron-app my-vite-app --template=vite-typescript -> Electron Forge version Fail

### ISSUE THREAD

**Issue by giuliettiseba** [caoxiemeihao/electron-forge-vite#3]
✖ Template (base) is not compatible with this version of Electron Forge (6.1.0), it requires 6.0.5
◼ Initializing template
◼ Installing template dependencies

An unhandled rejection has occurred inside Forge:
Error: Template (base) is not compatible with this version of Electron Forge (6.1.0), it requires 6.0.5
at validateTemplate (C:\Users\sgiu\AppData\Local\npm-cache\_npx\36f5f21e8c68ce75\node_modules\@electron-forge\core\dist\api\init.js:47:15)
    at async Task.task (C:\Users\sgiu\AppData\Local\npm-cache\_npx\36f5f21e8c68ce75\node_modules\@electron-forge\core\dist\api\init.js:73:17)
    at async Task.run (C:\Users\sgiu\AppData\Local\npm-cache\_npx\36f5f21e8c68ce75\node_modules\listr2\dist\index.cjs:978:11)
    at async C:\Users\sgiu\AppData\Local\npm-cache\_npx\36f5f21e8c68ce75\node_modules\p-map\index.js:57:22

**Comment by caoxiemeihao** [comment]
You need install the template into global before start, because the Electron forge has not yet released the vite template.

```sh
npm i -g electron-forge-template-vite-typescript
```

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/228873588-c7be80e5-3d47-4420-9c92-8d172a3b904d.png">

I received a query for `6.1.0` and I selected yes.

**Comment by caoxiemeihao** [comment]
Hey 👋
electron forge [v6.1.1](https://github.com/electron/forge/releases/tag/v6.1.1) is out!
